description: "The tax year the data applies to. The start year and end year must not span two tax years. No gaps are allowed, for example, 2020-22 is not valid. The minimum tax year is 2017-18."
type: string
example: "2021-22"