description: "The tax year the data applies to, for example, 2021-22. The start year and end year must not span two tax years. No gaps are allowed, for example, 2021-23 is not valid."
type: string
example: "2021-22"