is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Delete Insurance Policies Income [test only]
description: "This endpoint allows the developer to delete insurance policies financial income for less common types of income.<br><br>• Life Insurance Policies<br>• Life Annuity Contracts<br>• Capital Redemption Policies<br>• Voided ISAs<br>• Foreign Policies"
(annotations.sandboxData): !include ../scenarios/insurancePolicies/delete.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
responses:
  204:
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
