is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.formatCustomerRef
  - errors.formatCountryCode
  - errors.ruleCountryCode
  - errors.formatValue
  - errors.incorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Create and Amend Foreign Income [test only]
description: "This endpoint allows the developer to create and amend foreign income: foreign earnings and unremittable foreign income.  A National Insurance number and tax year must be provided."
(annotations.sandboxData): !include ../../scenarios/foreignIncome/put.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
   application/json:
      type: !include ../../schemas/foreign_amend_request.json
      examples:
        full_amendment:
          description: Full Foreign Income Amendment
          value: !include ../../examples/foreignIncome/amend_foreign_request.json
responses:
  200:
    body:
      application/json:
        type: !include ../../schemas/foreign_amend_response.json
        example: !include ../../examples/foreignIncome/amend_foreign_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.