is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Retrieve Foreign Income [test only]
description: "This endpoint allows the developer to retrieve foreign income: foreign earnings and unremittable foreign income."
(annotations.sandboxData): !include ../../scenarios/foreignIncome/get.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.
    body:
      application/json:
        type: !include ../../schemas/foreign_retrieve_response.json
        example: !include ../../examples/foreignIncome/retrieve_foreign_response.json