openapi: "3.0.3"

info:
  version: "2.0"
  title: Individuals Income Received (MTD)
  description: |
    # Send fraud prevention data
    HMRC monitors transactions to help protect your customers' confidential data from criminals and fraudsters. 
    
    <div class="govuk-warning-text warning-icon-fix">
      <span class="govuk-warning-text__icon warning-icon-ui-fix" aria-hidden="true">!</span>
      <strong class="govuk-warning-text__text">
        <span class="govuk-warning-text__assistive">Warning</span>
        You are required by law to submit header data for this API. This includes all associated APIs and endpoints.
      </strong>
    </div>
    
    [Check the data you need to send](/guides/fraud-prevention/). You can also use the [Test API](/api-documentation/docs/api/service/txm-fph-validator-api/1.0) during initial development and as part of your quality assurance checks.
    
    # Changelog
    The changelog is [available here](https://github.com/hmrc/income-tax-mtd-changelog).
    
    # Support
    
    * Raise non-technical or platform-related issues with the [Software Development Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).
    * Raise technical issues on the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues) GitHub page.

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production

components:
  securitySchemes:
    User-Restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access

tags:
  - name: Employments
    description: Resources relating to an individual's employments (please note, an occupational pension is classed as employment income and is identified by the occupationalPension property) <br><br> When using the <strong>STATEFUL</strong> Gov-Test-Scenario in the sandbox environment, <strong>a Custom Employment must be added before submitting Employment Financial Details.</strong>
     Providing financial details without adding Custom Employment will result in a HTTP 404 (matching resource not found) error being returned.<br><br>

  - name: Non-PAYE Employment Income
    description: These endpoints allow a user to create, amend, retrieve and delete Non-PAYE employment income and tips

  - name: Other Employment Income
    description: Resources relating to an individual's other employment income

  - name: Dividends Income
    description: These endpoints allow a user to create, amend, retrieve and delete Dividends

  - name: UK Dividends Income
    description: Resources relating to an individual's uk dividends

  - name: Foreign Income
    description: Resources relating to an individual's employments

  - name: Insurance Policies Income
    description: Resources relating to an individual's insurance policies

  - name: Pensions Income
    description: Resources relating to an individual's pensions income (please note, an occupational pension is classed as pensions income and is identified by the occupationalPension property)

  - name: Other Income
    description: Resources relating to an individual’s other income

  - name: UK Savings Account
    description: Resources relating to an individual’s UK savings account

  - name: Savings Income
    description: Resources relating to an individual's savings income

  - name: Capital Gains on Residential Property Disposals
    description: |
      These endpoints allow a user to create, delete or amend Capitals Gains income from residential property disposals
      
      Resources relating to an individual's residential property disposals

  - name: Other Capital Gains and Disposals
    description: |
      These endpoints allow a user to create, delete or amend income from other Capital Gains and disposals
    
      Resources relating to an individual's other capital gains and disposals

paths:
  /individuals/income-received/employments/{nino}/{taxYear}:
    $ref: "./employments.yaml"
  /individuals/income-received/employments/{nino}/{taxYear}/{employmentId}:
    $ref: "./employments_id.yaml"
  /individuals/income-received/employments/{nino}/{taxYear}/{employmentId}/ignore:
    $ref: "./employments_ignore.yaml"
  /individuals/income-received/employments/{nino}/{taxYear}/{employmentId}/unignore:
    $ref: "./employments_unignore.yaml"
  /individuals/income-received/employments/{nino}/{taxYear}/{employmentId}/financial-details:
    $ref: "./employments_financial_details.yaml"
  /individuals/income-received/employments/non-paye/{nino}/{taxYear}:
    $ref: "./employments_non_paye.yaml"
  /individuals/income-received/employments/other/{nino}/{taxYear}:
    $ref: "./employments_other.yaml"
  /individuals/income-received/dividends/{nino}/{taxYear}:
    $ref: "./dividends.yaml"
  /individuals/income-received/uk-dividends/{nino}/{taxYear}:
    $ref: "./uk_dividends.yaml"
  /individuals/income-received/foreign/{nino}/{taxYear}:
    $ref: "./foreign.yaml"
  /individuals/income-received/insurance-policies/{nino}/{taxYear}:
    $ref: "./insurance.yaml"
  /individuals/income-received/pensions/{nino}/{taxYear}:
    $ref: "./pensions.yaml"
  /individuals/income-received/other/{nino}/{taxYear}:
    $ref: "./other.yaml"
  /individuals/income-received/savings/uk-accounts/{nino}:
    $ref: "./savings_uk_accounts.yaml"
  /individuals/income-received/savings/uk-accounts/{nino}/{taxYear}/{savingsAccountId}:
    $ref: "./savings_uk_accounts_id.yaml"
  /individuals/income-received/savings/{nino}/{taxYear}:
    $ref: "./savings.yaml"
  /individuals/income-received/disposals/residential-property/{nino}/{taxYear}:
    $ref: "./cgt_residential.yaml"
  /individuals/income-received/disposals/residential-property/{nino}/{taxYear}/ppd:
    $ref: "./cgt_residential_ppd.yaml"
  /individuals/income-received/disposals/other-gains/{nino}/{taxYear}:
    $ref: "./cgt_other.yaml"
