is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.formatSource
  - errors.notFound
  - queryParameters.source
displayName: Retrieve Non-PAYE Employment Income
description: "This endpoint allows a developer to retrieve Non-PAYE employment income. A National Insurance number and tax year must be provided."
(annotations.sandboxData): !include ../../scenarios/nonPayeEmployments/nonPayeRetrieve.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.
    body:
      application/json:
        type: !include ../../schemas/non_paye_employment_income_retrieve_response.json
        examples:
          example-1:
            description: User provided Non-PAYE employment income
            value: !include ../../examples/nonPayeEmployments/retrieve_user_response.json
          example-2:
            description: HMRC held Non-PAYE employment income
            value: !include ../../examples/nonPayeEmployments/retrieve_hmrc_response.json
          example-3:
            description: Latest Non-PAYE employment income
            value: !include ../../examples/nonPayeEmployments/retrieve_latest_response.json