is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatEmploymentId
  - errors.formatSource
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - queryParameters.source
displayName: Retrieve an Employment and its Financial Details
description: "This endpoint enables you to retrieve employment information and associated financial data for a given tax year. A National Insurance number, tax year and Employment ID must be provided."
(annotations.sandboxData): !include ../../../scenarios/employments/financialDetailsRetrieve.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.
    body:
      application/json:
        type: !include ../../../schemas/employments_financial_retrieve_response.json
        examples:
          example-1:
            description: User provided financial details
            value: !include ../../../examples/employments/financialDetails/retrieve_user_response.json
          example-2:
            description: HMRC held financial details
            value: !include ../../../examples/employments/financialDetails/retrieve_hmrc_response.json
