is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.formatValue
  - errors.formatDate
  - errors.formatCustomerRef
  - errors.ruleCompletionDateBeforeDisposalDate
  - errors.ruleAcquisitionDateAfterDisposalDate
  - errors.ruleCompletionDate
  - errors.nonPpdRuleDisposalDate
  - errors.incorrectOrEmptyBody
  - errors.ruleGainLoss
  - errors.ruleLossesGreaterThanGain
  - errors.clientOrAgentNotAuthorised

displayName: Create and Amend CGT Residential Property Disposals (non-PPD)
description: "This endpoint allows the developer to submit residential property disposals that are not reported via the Report and pay Capital Gains Tax on UK property service for a given NINO and tax year for non payment for property disposals (non-PPD).
              The disposal date must be within the specified tax year. The completion date must be within the specific tax year and not in the future. If the specified tax year has not ended, the completion date must be between 7th March and 5th April."
(annotations.sandboxData): !include ../../../scenarios/defaultOnly.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
   application/json:
      type: !include ../../../schemas/cgt_non_ppd_create_amend_request.json
      examples:
        full_amendment:
          description: Full CGT Non PPD Amendment
          value: !include ../../../examples/cgt/residentialProperty/create_amend_non_ppd_request.json
responses:
  200:
    body:
      application/json:
        type: !include ../../../schemas/cgt_non_ppd_create_amend_response.json
        example: !include ../../../examples/cgt/residentialProperty/create_amend_non_ppd_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
