is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearRangeInvalid
  - errors.formatSource
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
  - queryParameters.source
displayName: Retrieve all CGT Residential Property Disposals and Overrides
description: | 
  This API provides the capability to retrieve the residential property disposals subject to capital gains tax for 
  payment for property disposal (PPD) and non payment for property disposal (non-PPD).  This includes:
  
    - User submitted residential property disposals
    - Disposals previously reported via the HMRC 'Report and Pay Capital Gains Tax on UK Property'
    - User submitted disposal overrides
(annotations.sandboxData): !include ../../../scenarios/cgt/disposalsAndOverridesRetrieve.md
(annotations.scope): "read:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include ../../../schemas/cgt_retrieve_all_property_disposals_overrides.json
        example: !include ../../../examples/cgt/residentialProperty/retrieve_property_disposal_submission_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.