#%RAML 1.0
---
title: Individuals Income Received (MTD)
description: This is a draft spec for the Individuals Income Received API.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/hal

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include docs/errors.md
 - title: Changelog
   content: !include docs/changelog.md
 - title: Support
   content: !include docs/support.md
 - title: Testing
   content: !include docs/testing.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
  errors: errors.raml
  headers: headers.raml

'/individuals/income-received':
  uriParameters:
    nino:
      description: "National Insurance number, in the format AA999999A."
      type: string
      example: "TC663795B"
    taxYear:
      description: "The tax year the data applies to, for example, 2019-20. The start year and end year must not span two tax years. No gaps are allowed, for example, 2019-21 is not valid."
      example: "2017-18"
  /foreign:
    (annotations.group):
       name: Foreign Income
       description: Resources relating to an individual's foreign income
    /{nino}:
      /{taxYear}:
        put: !include endpoints/foreign/amend.raml
        get: !include endpoints/foreign/retrieve.raml
        delete: !include endpoints/foreign/delete.raml
  /insurance-policies:
    (annotations.group):
       name: Insurance Policies Income
       description: Resources relating to an individual's insurance policies income
    /{nino}:
      /{taxYear}:
        put: !include endpoints/insurancePolicies/amend.raml
        get: !include endpoints/insurancePolicies/retrieve.raml
        delete: !include endpoints/insurancePolicies/delete.raml
  /pensions:
    (annotations.group):
       name: Pensions Income
       description: Resources relating to an individual's pensions income
    /{nino}:
      /{taxYear}:
        put: !include endpoints/pensions/amend.raml
        get: !include endpoints/pensions/retrieve.raml
        delete: !include endpoints/pensions/delete.raml
  /other:
    (annotations.group):
       name: Other Income
       description: Resources relating to an individual's other income
    /{nino}:
      /{taxYear}:
        put: !include endpoints/other/amend.raml
        get: !include endpoints/other/retrieve.raml
        delete: !include endpoints/other/delete.raml
  /savings:
    (annotations.group):
       name: Savings Income
       description: Resources relating to an individual's savings income
    /{nino}:
      /{taxYear}:
        put: !include endpoints/savings/amend.raml
        get: !include endpoints/savings/retrieve.raml
        delete: !include endpoints/savings/delete.raml