#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            example:
              description: 'The supplied income source could not be found.'
              value:
                code: MATCHING_RESOURCE_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: 'The format of the supplied NINO field is not valid.'
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: 'The format of the supplied tax year field is not valid.'
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: 'An empty or non-matching body was submitted.'
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: 'The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.'
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearNotSupportedMinus4Years:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupportedMinus4Years:
                description: "The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value. The tax year must not exceed current tax year minus 4."
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeInvalid:
                description: 'Tax year range invalid. A tax year range of one year is required.'
                value:
                  code: RULE_TAX_YEAR_RANGE_INVALID
  formatValue:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatValue:
                description: 'One or more values have been added with the incorrect format.'
                value:
                  code: FORMAT_VALUE
  formatCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCountryCode:
                description: 'The format of the supplied country code is not valid.'
                value:
                  code: FORMAT_COUNTRY_CODE
  ruleCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCountryCode:
                description: 'Not a valid ISO 3166-1 alpha-3 country code.'
                value:
                  code: RULE_COUNTRY_CODE
  formatCustomerRef:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCustomerRef:
                description: 'The format of the supplied customer reference is not valid.'
                value:
                  code: FORMAT_CUSTOMER_REF
  formatEvent:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatEvent:
                description: 'The format of policy event is not valid.'
                value:
                  code: FORMAT_EVENT
  formatQOPsRef:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatQOPsRef:
                description: 'The format of QOPS reference number is not valid.'
                value:
                  code: FORMAT_QOPS_REF
  formatDoubleTaxationArticle:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatDoubleTaxationArticle:
                  description: 'The format of double taxation article is not valid.'
                  value:
                    code: FORMAT_DOUBLE_TAXATION_ARTICLE
  formatDoubleTaxationTreaty:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatEvent:
                    description: 'The format of double taxation treaty is not valid.'
                    value:
                      code: FORMAT_DOUBLE_TAXATION_TREATY
  formatSF74Ref:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatSF74Ref:
                    description: 'The format of SF74 reference is not valid.'
                    value:
                      code: FORMAT_SF74_REF
  formatEmployerName:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatEmployerName:
                    description: 'The format of the employer name is not valid.'
                    value:
                      code: FORMAT_EMPLOYER_NAME
  formatEmployerRef:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatEmployerRef:
                    description: 'The format of the supplied employer ref is not valid.'
                    value:
                      code: FORMAT_EMPLOYER_REF
  formatDate:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatDate:
                    description: 'The supplied date format is not valid.'
                    value:
                      code: FORMAT_DATE
  formatClassOfSharesAwarded:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatClassOfSharesAwarded:
                    description: 'The format of class of shares awarded is not valid.'
                    value:
                      code: FORMAT_CLASS_OF_SHARES_AWARDED
  formatClassOfSharesAcquired:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatClassOfSharesAcquired:
                    description: 'The format of class of shares acquired is not valid.'
                    value:
                      code: FORMAT_CLASS_OF_SHARES_ACQUIRED
  formatSchemePlanType:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatSchemePlanType:
                    description: 'The format or value of scheme plan type is not valid.'
                    value:
                      code: FORMAT_SCHEME_PLAN_TYPE
  formatEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatEmploymentId:
                description: 'The format of the supplied employment ID field is not valid.'
                value:
                  code: FORMAT_EMPLOYMENT_ID
  formatStartDate:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatStartDate:
                  description: 'The format of the supplied start date field is not valid.'
                  value:
                    code: FORMAT_START_DATE
  formatCessationDate:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatCessationDate:
                    description: 'The format of the supplied cessation date is not valid.'
                    value:
                      code: FORMAT_CESSATION_DATE
  formatPayrollId:
          responses:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    formatPayrollId:
                      description: 'The format of the supplied payroll ID field is not valid.'
                      value:
                        code: FORMAT_PAYROLL_ID
  emptyOrIncorrectBody:
          responses:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    emptyOrIncorrectBody:
                      description: 'An empty or non-matching body was submitted.'
                      value:
                        code: RULE_EMPTY_OR_INCORRECT_BODY_SUBMITTED
  cessationDateBeforeStartDate:
          responses:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    cessationDateBeforeStartDate:
                      description: 'The cessation date is earlier than the start date.'
                      value:
                        code: RULE_END_DATE_BEFORE_START_DATE
  startDateAfterTaxYearEnd:
            responses:
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      startDateAfterTaxYearEnd:
                        description: 'The employment is listed as starting after the tax year ended.'
                        value:
                          code: RULE_START_DATE_AFTER_TAX_YEAR_END
  cessationDateBeforeTaxYearStart:
              responses:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        cessationDateBeforeTaxYearStart:
                          description: 'The employment is listed as ending before the tax year began.'
                          value:
                            code: RULE_CESSATION_DATE_BEFORE_TAX_YEAR_START
  ruleCustomEmployment:
              responses:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        ruleCustomEmployment:
                          description: 'The Employment ID provided is for a custom (user-provided) employment.'
                          value:
                            code: RULE_CUSTOM_EMPLOYMENT
  ruleTaxYearNotEnded:
              responses:
                400:
                  body:
                    application/json:
                      type: types.errorResponse
                      examples:
                        ruleTaxYearNotEnded:
                          description: 'The submission has been made before the tax year it relates to has ended.'
                          value:
                            code: RULE_TAX_YEAR_NOT_ENDED
  formatSource:
          responses:
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    formatSource:
                      description: 'The format of the supplied source is not valid.'
                      value:
                        code: FORMAT_SOURCE
