#%RAML 1.0 Library

uses:
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  notFound:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFound:
                description: 'The supplied income source could not be found.'
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  notFoundOtherCgtAndDisposals:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFoundOtherCgtAndDisposals:
                description: 'Other Capital Gains and disposals could not be found for the supplied nino and taxYear.'
                value:
                  code: MATCHING_RESOURCE_NOT_FOUND
  notFoundCgtOverrides:
      responses:
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                notFoundCgtOverrides:
                  description: 'There are no submissions found.'
                  value:
                    code: MATCHING_RESOURCE_NOT_FOUND
  notFoundPpdSubmissionId:
    responses:
      404:
        body:
          application/json:
            type: types.errorResponse
            examples:
              notFoundPpdSubmissionId:
                description: 'The PPD submission ID was not found.'
                value:
                  code: PPD_SUBMISSION_ID_NOT_FOUND
  clientOrAgentNotAuthorised:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              clientOrAgentNotAuthorised:
                description: 'The client or agent is not authorised. This is because: the client is not subscribed to MTD, the agent is not subscribed to Agent Services, or the client has not authorised the agent to act on their behalf.'
                value:
                  code: CLIENT_OR_AGENT_NOT_AUTHORISED
  formatNino:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatNino:
                description: 'The format of the supplied NINO field is not valid.'
                value:
                  code: FORMAT_NINO
  formatTaxYear:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatTaxYear:
                description: 'The format of the supplied tax year field is not valid.'
                value:
                  code: FORMAT_TAX_YEAR
  incorrectOrEmptyBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              incorrectOrEmptyBody:
                description: 'An empty or non-matching body was submitted.'
                value:
                  code: RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED
  ruleTaxYearNotSupported:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupported:
                description: 'The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value.'
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearNotSupportedMinus4Years:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              rule_TaxYearNotSupportedMinus4Years:
                description: "The specified tax year is not supported. That is, the tax year specified is before the minimum tax year value. The tax year must not exceed current tax year minus 4."
                value:
                  code: RULE_TAX_YEAR_NOT_SUPPORTED
  ruleTaxYearRangeInvalid:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearRangeInvalid:
                description: 'Tax year range invalid. A tax year range of one year is required.'
                value:
                  code: RULE_TAX_YEAR_RANGE_INVALID
  formatValue:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatValue:
                description: 'One or more values have been added with the incorrect format.'
                value:
                  code: FORMAT_VALUE
  formatCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCountryCode:
                description: 'The format of the supplied country code is not valid.'
                value:
                  code: FORMAT_COUNTRY_CODE
  ruleCountryCode:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCountryCode:
                description: 'Not a valid ISO 3166-1 alpha-3 country code.'
                value:
                  code: RULE_COUNTRY_CODE
  formatCustomerRef:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatCustomerRef:
                description: 'The format of the supplied customer reference is not valid.'
                value:
                  code: FORMAT_CUSTOMER_REF
  formatEvent:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatEvent:
                description: 'The format of policy event is not valid.'
                value:
                  code: FORMAT_EVENT
  formatQOPsRef:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatQOPsRef:
                description: 'The format of QOPS reference number is not valid.'
                value:
                  code: FORMAT_QOPS_REF
  formatDoubleTaxationArticle:
      responses:
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
                formatDoubleTaxationArticle:
                  description: 'The format of double taxation article is not valid.'
                  value:
                    code: FORMAT_DOUBLE_TAXATION_ARTICLE
  formatDoubleTaxationTreaty:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatEvent:
                    description: 'The format of double taxation treaty is not valid.'
                    value:
                      code: FORMAT_DOUBLE_TAXATION_TREATY
  formatSF74Ref:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatSF74Ref:
                    description: 'The format of SF74 reference is not valid.'
                    value:
                      code: FORMAT_SF74_REF
  formatEmployerName:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatEmployerName:
                    description: 'The format of the employer name is not valid.'
                    value:
                      code: FORMAT_EMPLOYER_NAME
  formatEmployerRef:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatEmployerRef:
                    description: 'The format of the supplied employer ref is not valid.'
                    value:
                      code: FORMAT_EMPLOYER_REF
  formatDate:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatDate:
                    description: 'The supplied date format is not valid.'
                    value:
                      code: FORMAT_DATE
  formatClassOfSharesAwarded:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatClassOfSharesAwarded:
                    description: 'The format of class of shares awarded is not valid.'
                    value:
                      code: FORMAT_CLASS_OF_SHARES_AWARDED
  formatClassOfSharesAcquired:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatClassOfSharesAcquired:
                    description: 'The format of class of shares acquired is not valid.'
                    value:
                      code: FORMAT_CLASS_OF_SHARES_ACQUIRED
  formatSchemePlanType:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatSchemePlanType:
                    description: 'The format or value of scheme plan type is not valid.'
                    value:
                      code: FORMAT_SCHEME_PLAN_TYPE
  formatEmploymentId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatEmploymentId:
                description: 'The format of the supplied employment ID field is not valid.'
                value:
                  code: FORMAT_EMPLOYMENT_ID
  formatStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatStartDate:
                description: 'The format of the supplied start date field is not valid.'
                value:
                  code: FORMAT_START_DATE
  formatCessationDate:
        responses:
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  formatCessationDate:
                    description: 'The format of the supplied cessation date is not valid.'
                    value:
                      code: FORMAT_CESSATION_DATE
  formatPayrollId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatPayrollId:
                description: 'The format of the supplied payroll ID field is not valid.'
                value:
                  code: FORMAT_PAYROLL_ID
  formatPpdSubmissionId:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatPpdSubmissionId:
                description: 'The format of the supplied PPD submission ID is invalid.'
                value:
                  code: FORMAT_PPD_SUBMISSION_ID
  emptyOrIncorrectBody:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              emptyOrIncorrectBody:
                description: 'An empty or non-matching body was submitted.'
                value:
                  code: RULE_EMPTY_OR_INCORRECT_BODY_SUBMITTED
  cessationDateBeforeStartDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              cessationDateBeforeStartDate:
                description: 'The cessation date is earlier than the start date.'
                value:
                  code: RULE_END_DATE_BEFORE_START_DATE
  startDateAfterTaxYearEnd:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              startDateAfterTaxYearEnd:
                description: 'The employment is listed as starting after the tax year ended.'
                value:
                  code: RULE_START_DATE_AFTER_TAX_YEAR_END
  cessationDateBeforeTaxYearStart:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              cessationDateBeforeTaxYearStart:
                description: 'The employment is listed as ending before the tax year began.'
                value:
                  code: RULE_CESSATION_DATE_BEFORE_TAX_YEAR_START
  ruleCustomEmployment:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCustomEmployment:
                description: 'The Employment ID provided is for a custom (user-provided) employment.'
                value:
                  code: RULE_CUSTOM_EMPLOYMENT
  ruleTaxYearNotEnded:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleTaxYearNotEnded:
                description: 'The submission has been made before the tax year it relates to has ended.'
                value:
                  code: RULE_TAX_YEAR_NOT_ENDED
  ruleAmountGainLoss:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleAmountGainLoss:
                description: 'Either amountOfGain or amountOfLoss, must be provided but not both.'
                value:
                  code: RULE_AMOUNT_GAIN_LOSS
  ruleLossesGreaterThanGain:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleLossesGreaterThanGain:
                description: 'The total losses from this year or the previous year must not be greater than the gain.'
                value:
                  code: RULE_LOSSES_GREATER_THAN_GAIN
  formatSource:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              formatSource:
                description: 'The format of the supplied source is not valid.'
                value:
                  code: FORMAT_SOURCE
  ruleLumpSums:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleLumpSums:
                description: 'Where lumpSums have been provided at least one child object is required.'
                value:
                  code: RULE_LUMP_SUMS
  ruleGainLoss:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleGainLoss:
                description: 'Only one of gain or loss values can be provided.'
                value:
                  code: RULE_GAIN_LOSS
  cgtOtherFormatAssetDescription:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              cgtOtherFormatAssetDescription:
                description: 'The format of the supplied asset description is not valid.'
                value:
                  code: FORMAT_ASSET_DESCRIPTION
  cgtOtherFormatAssetType:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              cgtOtherFormatAssetType:
                description: 'The format of the supplied assetType value is invalid.'
                value:
                  code: FORMAT_ASSET_TYPE
  cgtOtherFormatClaimOrElectionCodes:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              cgtOtherFormatClaimOrElectionCodes:
                description: 'The format of the supplied claimOrElectionCodes value is invalid.'
                value:
                  code: FORMAT_CLAIM_OR_ELECTION_CODES
  cgtOtherRuleDisposalDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleDisposalDate:
                description: "The disposalDate must be in the specified tax year and no later than today's date."
                value:
                  code: RULE_DISPOSAL_DATE
  nonPpdRuleDisposalDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              nonPpdRuleDisposalDate:
                description: "The disposalDate must be within the specified tax year."
                value:
                  code: RULE_DISPOSAL_DATE
  cgtOtherRuleAcquisitionDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              cgtOtherRuleAcquisitionDate:
                description: 'The acquisitionDate must not be later than disposalDate.'
                value:
                  code: RULE_ACQUISITION_DATE
  cgtOtherRuleGainAfterReliefLossAfterRelief:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              cgtOtherRuleGainAfterReliefLossAfterRelief:
                description: 'Only one of gainAfterRelief or lossAfterRelief values can be provided.'
                value:
                  code: RULE_GAIN_AFTER_RELIEF_LOSS_AFTER_RELIEF
  ruleCompletionDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCompletionDate:
                description: 'The completionDate must be within the specific tax year and not in the future. If the specified tax year has not ended, the completionDate must be between 7th March and 5th April.'
                value:
                  code: RULE_COMPLETION_DATE
  ruleCompletionDateBeforeDisposalDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleCompletionDateBeforeDisposalDate:
                description: 'The completionDate must not be earlier than the disposalDate.'
                value:
                  code: RULE_COMPLETION_DATE_BEFORE_DISPOSAL_DATE
  ruleAcquisitionDateAfterDisposalDate:
    responses:
      400:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleAcquisitionDateAfterDisposalDate:
                description: 'The acquisitionDate must not be later than disposalDate.'
                value:
                  code: RULE_ACQUISITION_DATE_AFTER_DISPOSAL_DATE
  ruleUpdateForbidden:
    responses:
      403:
        body:
          application/json:
            type: types.errorResponse
            examples:
              ruleUpdateForbidden:
                description: 'The update for an HMRC held employment is not permitted.'
                value:
                  code: RULE_UPDATE_FORBIDDEN
  ruleDuplicatedPpdSubmissionId:
    responses:
      400:
        body:
         application/json:
            type: types.errorResponse
            examples:
              ruleDuplicatedPpdSubmissionId:
                description: 'A PPD submission ID must only be used once.'
                value:
                  code: RULE_DUPLICATED_PPD_SUBMISSION_ID
  ruleIncorrectDisposalType:
    responses:
      403:
        body:
         application/json:
            type: types.errorResponse
            examples:
              ruleIncorrectDisposalType:
                description: 'A PPD submission ID in the request is being used for the incorrect disposal type.'
                value:
                  code: RULE_INCORRECT_DISPOSAL_TYPE
  ruleDeleteForbidden:
    responses:
      403:
        body:
         application/json:
            type: types.errorResponse
            examples:
              ruleDeleteForbidden:
                description: 'A deletion for an HMRC held employment is not permitted.'
                value:
                  code: RULE_DELETE_FORBIDDEN
  formatAccountName:
    responses:
     400:
       body:
         application/json:
           type: types.errorResponse
           examples:
             formatAccountName:
               description: 'The format of the supplied account name field is not valid.'
               value:
                 code: FORMAT_ACCOUNT_NAME
  maximumSavingsAccountLimit:
   responses:
    403:
      body:
        application/json:
          type: types.errorResponse
          examples:
            maximumSavingsAccountLimit:
              description: 'The maximum number of 1000 savings accounts exceeded.'
              value:
                code: RULE_MAXIMUM_SAVINGS_ACCOUNTS_LIMIT
  formatSavingsAccountId:
   responses:
    400:
     body:
      application/json:
       type: types.errorResponse
       examples:
        formatSavingsAccountId:
         description: 'The format of the supplied savings account ID is not valid'
         value:
          code: FORMAT_SAVINGS_ACCOUNT_ID
  duplicateAccountName:
   responses:
    403:
      body:
        application/json:
          type: types.errorResponse
          examples:
            duplicateAccountName:
              description: 'A duplicate account name was supplied for that National Insurance Number.'
              value:
                code: RULE_DUPLICATE_ACCOUNT_NAME
