is:
  - headers.acceptJson
  - headers.contentTypeJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatValue
  - errors.formatDate
  - errors.cgtOtherFormatAssetDescription
  - errors.cgtOtherFormatAssetType
  - errors.cgtOtherFormatClaimOrElectionCodes
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.cgtOtherRuleDisposalDate
  - errors.cgtOtherRuleAcquisitionDate
  - errors.ruleGainLoss
  - errors.cgtOtherRuleGainAfterReliefLossAfterRelief
  - errors.incorrectOrEmptyBody
  - errors.clientOrAgentNotAuthorised
displayName: Create and Amend Other Capital Gains and Disposals [test only]
description: This endpoint allows the developer to submit other Capital Gains disposals with the exception of residential property, for a given NINO and tax year
(annotations.sandboxData): !include ../../../scenarios/defaultOnly.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
body:
   application/json:
      type: !include ../../../schemas/capital_gains_other_amend_request.json
      examples:
        full_amendment:
          description: Other Capital Gains and Disposals with Gains
          value: !include ../../../examples/cgt/other/amend_request.json
responses:
  200:
    body:
      application/json:
        type: !include ../../../schemas/capital_gains_other_amend_response.json
        example: !include ../../../examples/cgt/other/amend_response.json
    headers:
      X-CorrelationId:
        example: c75f40a6-a3df-4429-a697-471eeec46435
        description: Unique ID for operation tracking <br> String, 36 characters.
